POST http://localhost:3005/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMzQ1IiwiaWQiOiI2MGYwNjZiNDkwZTcyNTcxNWEyNmVjNDAiLCJpYXQiOjE2MjYzNjc3MDF9.uS89cdZNMvsto_OtLtBwFjbEuA7r2GkRenImNwAmFpI

{
  "title": "1112",
  "url": "1112",
  "author": "1112",
  "user": "60f066b490e725715a26ec40"
}

###

POST http://localhost:3005/api/users
Content-Type: application/json

{
  "name": "quest",
  "username": "quest",
  "password": "quest",
  "blogs": []
}

###

POST http://localhost:3005/api/login
Content-Type: application/json

{
  "username": "nipaldi",
  "password": "12345"
}

###

POST http://localhost:3007/api/testing/reset

### 
POST http://localhost:3005/api/blogs/60f19aad49a22f2463ff2927/comments
Content-Type: application/json
 
{
  "comment": "moi2"
}